### ISSUE TITLE
Code for multilingual alignment is misssing in `make_data_module`

### ISSUE THREAD

**Issue by luciusssss** [Saltychtao/PreAlign#1]
Hi! I like the multilingual alignment technique proposed in your paper and I want to try it in practice.
But some code seems to be missing.

In `src/multilingual_alignment.py`, the function `make_data_module` is called to prepare training data, with the argument `type` set to `"dictionary_contrastive"`.
https://github.com/Saltychtao/PreAlign/blob/4905aa542053d8c0276bd4b751d2db6b47e15f3e/src/multilingual_alignment.py#L133
However, in `make_data_module`, there is no code related to `"dictionary_contrastive"`:
https://github.com/Saltychtao/PreAlign/blob/4905aa542053d8c0276bd4b751d2db6b47e15f3e/src/data/__init__.py#L4-L8

Could you please check whether there is any problem with the code? Thank you!

**Comment by Saltychtao** [comment]
Hello, 

Thank you for your attention to our work!  It seems that we have uploaded an older version of our code,  which lacks several modules. Unfortunately, the newest version is now on the server of the internship team where I have left. I will try to contact the team to get the code, which might take one week and cannot be guaranteed to success. I will re-implement them if I cannot get the code, which might take 2 weeks. I am also willing to provide help regarding the other part of the repo.

**Comment by Saltychtao** [comment]
hello, we have updated the code in the new repo "https://github.com/NJUNLP/PreAlign.git". Feel free to raise issues in the new repo if you have more questions.
